#!/usr/bin/expect

set timeout 20
set ip "10.20.91.201"
set user "rtrd"
set password "qq123456"

spawn ssh $user@$ip "echo '--- 9x9 PROGRESS ---' && tail -n 5 ~/go-strategy-app/logs/build_9.log && echo '--- 13x13 PROGRESS ---' && tail -n 5 ~/go-strategy-app/logs/build_13.log && echo '--- 19x19 PROGRESS ---' && tail -n 5 ~/go-strategy-app/logs/build_19.log"
expect "password:" { send "$password\r" }
expect eof
